apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app
spec:
  selector:
    matchLabels:
      app: nestjs-app
  replicas: 2
  template:
    metadata:
      labels:
        app: nestjs-app
    spec:
      containers:
        - name: nestjs-app
          image: helaldckrhub/nestjs-app
          ports:
            - containerPort: 3000